name: .NET Core Build with Tests

on:
  push:
    branches: [ master ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     env:
#       config: 'Release'

#     strategy:
#       matrix:
#         solution: ['HelloUnitTestWorkFlow', 'SeriesOfSquares']
#       fail-fast: false    # Don't stop on fail (of tests)
#       max-parallel: 1     # Don't run parallel as it will create push conflict

jobs:
  first:
    uses: BioBoost/playground-csharp-xunit-github-action/.github/workflows/run_xunit_tests.yaml@d51b8b4da2337614b08002c44cf22de72ff369ce
    with:
      solution: 'HelloUnitTestWorkFlow'