name: .NET Core Build with Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
      report_file: 'report.md'
      
    steps:
    - uses: actions/checkout@v2

    # Setup the .NET Core environment
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101    
      
    # Install project dependencies
    - name: Install dependencies
      run: dotnet restore
      
    # Build the project
    - name: Build
      run: dotnet build --configuration $config --no-restore
      
    # Run the xUnit tests
    - name: Test PR      
      run: dotnet test --no-restore --no-build --configuration $config --logger:"liquid.md;LogFileName=${{github.workspace}}/$report_file;Title=Test Report;"
      
    # Commit the report to the repo
    - name: Commit files
      run: |
        git config --local user.name "xunit"
        git add ./TestReport
        git commit -m "Update the TestReport"
    
    # Push changes to the remote
    - name: Push changes # push the output folder to your repo
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # force: true