name: .NET Core Build with Tests

on:
  push:
    branches: [ master ]

### This works
# jobs:
#   first:
#     if: ${{always()}}
#     uses: BioBoost/playground-csharp-xunit-github-action/.github/workflows/run_xunit_tests.yaml@master
#     with:
#       solution: 'HelloUnitTestWorkFlow'

#   second:
#     needs: [first]
#     if: ${{always()}}
#     uses: BioBoost/playground-csharp-xunit-github-action/.github/workflows/run_xunit_tests.yaml@master
#     with:
#       solution: 'SeriesOfSquares'


# Apparently can't call workflow from matrix :(
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        solution: ['HelloUnitTestWorkFlow', 'SeriesOfSquares']
      fail-fast: false    # Don't stop on fail (of tests)
      max-parallel: 1     # Don't run parallel as it will create push conflict

    uses: BioBoost/playground-csharp-xunit-github-action/.github/workflows/run_xunit_tests.yaml@master
    with:
      solution: ${{matrix.solution}}
